# Generated by Django 4.2.27 on 2025-12-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/'),
        ),
    ]
